### ISSUE TITLE
Getting a few errors when running:

### ISSUE THREAD

**Issue by maurus56** [unnati-xyz/music-generation#1]
- No 'YourMusicLibrary' folder inside 'datasets' raising issue when trying to convert files.

When running test.py:

- TimeDistributedDense signaled as obsolete and son to be erased, prompts the user to apply TimeDistributed( Dense() ) <--- couldn't make it work (little knowledge on nn programming)
- The network as is, throws this error: 

    ```
    Using Theano backend.
    Loading training data
    Finished loading training data
    X_train shape:  (19, 40, 22050)
    y_train shape:  (19, 40, 22050)
    freq_space_dims= 22050
    Using Mean Absolute Error
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/layers/core.py:1205: UserWarning: `TimeDistributedDense` is deprecated, And will be removed on May 1st, 2017. Please use a `Dense` layer instead.
      warnings.warn('`TimeDistributedDense` is deprecated, '
    Traceback (most recent call last):
      File "train.py", line 31, in <module>
        model = network_utils.create_lstm_network(num_frequency_dimensions=freq_space_dims, num_hidden_dimensions=hidden_dims) #hidden_dims=1024
      File "/Users/maurolanza/Desktop/music-generation-master/nn_utils/network_utils.py", line 38, in create_lstm_network
        model.add(TimeDistributedDense(input_dim=num_frequency_dimensions, output_dim=num_hidden_dimensions))
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/models.py", line 299, in add
        layer.create_input_layer(batch_input_shape, input_dtype)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/engine/topology.py", line 401, in create_input_layer
        self(x)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/engine/topology.py", line 572, in __call__
        self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/engine/topology.py", line 635, in add_inbound_node
        Node.create_node(self, inbound_layers, node_indices, tensor_indices)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/engine/topology.py", line 166, in create_node
        output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/layers/core.py", line 1266, in call
        ' requires to know the length '
    ValueError: Layer timedistributeddense_1 requires to know the length of its input, but it could not be inferred automatically. Specify it manually by passing an input_shape argument to the first layer in your model.
    ```

When trying to fix it with a Reshape layer or other means it throws the error in the other layers, and when it doesn't throw any error when loading the net.. they come when starting the training.

Please some help.

**Comment by PadmajaVB** [comment]
I think the problem is with the Keras version. Please note that the project uses Keras version 0.1.0. Here's the link to download - https://github.com/fchollet/keras/tarball/0.1.0  
Hope it helps. :)
